version: '3'


services:
  database:
    image: neo4j:latest
    volumes:
      - ./data:/data:Z
      - ./logs:/logs:Z
      - ./import:/var/lib/neo4j/import:Z
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"
